### ISSUE TITLE
"Go to top" link spans entire page

### ISSUE THREAD

**Issue by njnatale-lm** [AlphaNodes/additionals#152]
Starts here: https://github.com/AlphaNodes/additionals/blob/main/assets/stylesheets/additionals.css#L41

The CSS for the "Go to top" link spans the entire page, meaning a user could click the link without realizing or intending for it to happen.

Offending section:

```css
.gototop {
  display: block;
  margin-top: 20px;
  padding: 10px 0;
  text-align: right;
  clear: both;
}
```

I think switching from `display: block` to `float: right` would be a great solution that keeps the link on the right side, but only activates the click if the user is actively hovering over the text.
